import { verifyAdmin, authedJson, adminDb } from "../../../../lib/adminAuth";
import { cloud } from "../../../../lib/cloudinary";

// Media library source of truth is Cloudinary itself (Admin API), so every
// file in the account appears here — including bulk imports that never went
// through the `media` DB table. The DB table is only used for alt text.
// `limit` stops early once enough items are collected (for a fast first
// paint); omit it to fetch everything.
async function listCloudinary(limit) {
  const items = [];
  const wantAll = !limit || limit <= 0;
  for (const resourceType of ["image", "video"]) {
    let nextCursor;
    do {
      const res = await cloud().search
        .expression(`resource_type:${resourceType}`)
        .sort_by("created_at", "desc")
        .max_results(500)
        .next_cursor(nextCursor)
        .execute();
      for (const r of res.resources || []) {
        items.push({
          id: r.public_id,
          public_id: r.public_id,
          url: r.secure_url,
          kind: resourceType === "video" ? "video" : "image",
          bytes: r.bytes || 0,
          duration: resourceType === "video" ? (r.duration || 0) : 0,
          format: r.format || "",
          width: r.width || 0,
          height: r.height || 0,
          created_at: r.created_at,
          folder: (r.public_id.split("/").slice(0, -1).join("/") || ""),
          // Video poster: first-frame JPG thumbnail generated by Cloudinary.
          thumb: resourceType === "video"
            ? cloud().url(r.public_id, { resource_type: "video", format: "jpg", transformation: [{ width: 640, crop: "limit" }, { start_offset: 1 }] })
            : r.secure_url,
        });
        if (!wantAll && items.length >= limit) break;
      }
      nextCursor = res.next_cursor;
    } while (nextCursor && (wantAll || items.length < limit));
    if (!wantAll && items.length >= limit) break;
  }
  items.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  return wantAll ? items : items.slice(0, limit);
}

export async function GET(request) {
  const user = await verifyAdmin(request);
  const denied = authedJson(user); if (denied) return denied;
  const { searchParams } = new URL(request.url);
  const limit = Math.max(0, parseInt(searchParams.get("limit") || "0", 10) || 0);
  const skipUsage = searchParams.get("usage") === "0";
  try {
    const [items, usageRes] = await Promise.all([
      listCloudinary(limit),
      skipUsage ? null : cloud().api.usage().catch(() => null),
    ]);
    // Alt text from the DB media table (best effort).
    const alts = {};
    try {
      const { data } = await adminDb().from("media").select("public_id,alt");
      for (const row of data || []) if (row.public_id) alts[row.public_id] = row.alt || "";
    } catch { /* ignore */ }
    const media = items.map((m) => ({ ...m, alt: alts[m.public_id] || "" }));

    let usage = null;
    if (usageRes) {
      const apiLimit = usageRes.limits?.storage?.limit ?? usageRes.plan?.storage ?? 0;
      // Plan limit from the API when present; otherwise the admin-configurable
      // setting (Admin → Settings → Media), defaulting to the 25 GB free plan.
      let limitGb = 25;
      try {
        const { data: srow } = await adminDb().from("site_settings").select("value").eq("key", "cloudinary_storage_limit_gb").single();
        const v = Number(srow?.value);
        if (Number.isFinite(v) && v > 0) limitGb = v;
      } catch { /* keep default */ }
      const limit = apiLimit > 0 ? apiLimit : Math.round(limitGb * 1073741824);
      const used = usageRes.storage?.usage ?? 0;
      usage = {
        used_bytes: used,
        limit_bytes: limit,
        available_bytes: Math.max(0, limit - used),
        used_mb: Math.round(used / 1048576),
        limit_mb: limit ? Math.round(limit / 1048576) : 0,
        plan: usageRes.plan || null,
      };
    }
    return Response.json({ media, usage });
  } catch (e) {
    return Response.json({ error: "Cloudinary error: " + e.message }, { status: 500 });
  }
}

export async function DELETE(request) {
  const user = await verifyAdmin(request);
  const denied = authedJson(user); if (denied) return denied;
  const { searchParams } = new URL(request.url);
  const id = searchParams.get("id"); // public_id (or legacy DB uuid)
  if (!id) return Response.json({ error: "Missing id" }, { status: 400 });
  const db = adminDb();

  // Resolve the public_id: it may be a DB uuid from older clients.
  let publicId = id;
  let kind = null;
  try {
    const { data } = await db.from("media").select("public_id,kind").eq("id", id).single();
    if (data?.public_id) { publicId = data.public_id; kind = data.kind; }
  } catch { /* not a DB id — treat as public_id */ }

  // Destroy from Cloudinary (try both resource types when unknown).
  const types = kind === "video" ? ["video"] : kind === "image" ? ["image"] : ["image", "video"];
  for (const t of types) {
    try { await cloud().uploader.destroy(publicId, { resource_type: t }); } catch { /* ignore */ }
  }
  try { await db.from("media").delete().eq("public_id", publicId); } catch { /* ignore */ }
  try { await db.from("media").delete().eq("id", id); } catch { /* ignore */ }
  return Response.json({ ok: true });
}

// POST /api/admin/media — register a file that was uploaded directly from the
// browser to Cloudinary (unsigned preset). Tiny JSON body; the heavy bytes
// never touch the serverless function. The media library lists from
// Cloudinary itself — this row only carries alt text for future editing.
export async function POST(request) {
  const user = await verifyAdmin(request);
  const denied = authedJson(user); if (denied) return denied;
  const { public_id, url, kind, alt } = await request.json().catch(() => ({}));
  if (!public_id || !url) return Response.json({ error: "Missing public_id/url" }, { status: 400 });
  try {
    const db = adminDb();
    // No unique constraint on public_id in older schemas — replace manually.
    await db.from("media").delete().eq("public_id", public_id);
    await db.from("media").insert({ public_id, url, kind: kind === "video" ? "video" : "image", alt: alt || "" });
  } catch { /* best effort */ }
  return Response.json({ ok: true });
}
