// Search index for the admin command-palette (AdminSearch).
// { title, href, section?, keywords } — section is the sub-section shown under the title.
// Keep keywords lowercase; matching is a simple case-insensitive substring.
export const ADMIN_SEARCH_INDEX = [
  { title: "Dashboard", href: "/admin", keywords: "home overview stats" },
  { title: "Leads & Enquiries", href: "/admin/leads", keywords: "leads enquiries contact form messages" },
  { title: "Homepage Manager", href: "/admin/homepage", keywords: "homepage hero banner sections" },
  { title: "Couple Stories", href: "/admin/couple-stories", keywords: "couple stories client stories weddings" },
  { title: "Artists", href: "/admin/artists", keywords: "artists celebrity singer actor management" },
  { title: "Portfolio / Events", href: "/admin/portfolio", keywords: "portfolio events shows" },
  { title: "Services", href: "/admin/services", keywords: "services" },
  { title: "Weddings", href: "/admin/weddings", keywords: "weddings destination wedding" },
  { title: "Gallery & Videos", href: "/admin/gallery", keywords: "gallery videos photos media" },
  { title: "Press Coverage", href: "/admin/press", keywords: "press news clippings coverage" },
  { title: "Clients", href: "/admin/clients", keywords: "clients logo wall companies" },
  { title: "Testimonials", href: "/admin/testimonials", keywords: "testimonials reviews feedback quotes" },
  { title: "Team", href: "/admin/team", keywords: "team staff members" },
  { title: "International Shows", href: "/admin/international", keywords: "international shows china" },
  { title: "Blog Posts", href: "/admin/posts", keywords: "blog posts articles news" },
  { title: "Landing Pages", href: "/admin/landing-pages", keywords: "landing pages" },
  { title: "SEO & Redirects", href: "/admin/seo", keywords: "seo meta redirects search" },
  { title: "Legal Pages", href: "/admin/legal", keywords: "legal privacy terms policy" },
  { title: "Navigation & Footer", href: "/admin/navigation", keywords: "navigation menu footer header links" },
  { title: "Media Library", href: "/admin/media", keywords: "media library photos videos upload" },
  { title: "Page Content", href: "/admin/content", keywords: "page content banners about" },
  { title: "Site Settings", href: "/admin/settings", keywords: "settings site config" },
  { title: "Announcement bar", section: "Site Settings", href: "/admin/settings#sec-announcement", keywords: "announcement banner strip notice top bar" },
  { title: "Homepage sections", section: "Site Settings", href: "/admin/settings#sec-home-sections", keywords: "homepage sections show hide toggle visible" },
  { title: "Hero video", section: "Site Settings", href: "/admin/settings#sec-hero", keywords: "hero video banner" },
  { title: "Website theme", section: "Site Settings", href: "/admin/settings#sec-theme", keywords: "theme colors colour palette" },
  { title: "Company & logo", section: "Site Settings", href: "/admin/settings#sec-company", keywords: "company logo name" },
  { title: "Contact info", section: "Site Settings", href: "/admin/settings#sec-contact", keywords: "contact phone email whatsapp" },
  { title: "Addresses", section: "Site Settings", href: "/admin/settings#sec-addresses", keywords: "address location office" },
  { title: "Social media", section: "Site Settings", href: "/admin/settings#sec-socials", keywords: "social instagram facebook youtube links" },
  { title: "Media storage", section: "Site Settings", href: "/admin/settings#sec-media", keywords: "media storage cloudinary limit space" },
  { title: "Cookie banner", section: "Site Settings", href: "/admin/settings#sec-privacy", keywords: "cookie banner privacy consent" },
  { title: "Integrations & AI", href: "/admin/integrations", keywords: "integrations ai gemini api key analytics" },
  { title: "Creative Studio", href: "/admin/creatives", keywords: "creative studio templates whatsapp share" },
  { title: "Media Tools", href: "/admin/media-tools", keywords: "media tools crop watermark video studio" },
  { title: "Billing", href: "/admin/billing", keywords: "billing quotes invoices receipts payment" },
  { title: "Launch Checklist", href: "/admin/launch", keywords: "launch checklist go live" },
];
