// Single source of truth for the admin sidebar.
// [icon, label, href] — add new modules here; app/admin/layout.js renders it.
export const ADMIN_NAV = [
  ["📊", "Dashboard", "/admin"],
  ["📩", "Leads & Enquiries", "/admin/leads"],
  ["🏠", "Homepage Manager", "/admin/homepage"],
  ["💑", "Couple Stories", "/admin/couple-stories"],
  ["🎤", "Artists", "/admin/artists"],
  ["🎪", "Portfolio / Events", "/admin/portfolio"],
  ["🧩", "Services", "/admin/services"],
  ["💒", "Weddings", "/admin/weddings"],
  ["🎞️", "Gallery & Videos", "/admin/gallery"],
  ["📰", "Press Coverage", "/admin/press"],
  ["🏢", "Clients", "/admin/clients"],
  ["⭐", "Testimonials", "/admin/testimonials"],
  ["👥", "Team", "/admin/team"],
  ["🌍", "International Shows", "/admin/international"],
  ["📝", "Blog Posts", "/admin/posts"],
  ["📍", "Landing Pages", "/admin/landing-pages"],
  ["🔍", "SEO & Redirects", "/admin/seo"],
  ["⚖️", "Legal Pages", "/admin/legal"],
  ["🧭", "Navigation & Footer", "/admin/navigation"],
  ["🖼️", "Media Library", "/admin/media"],
  ["📄", "Page Content", "/admin/content"],
  ["⚙️", "Site Settings", "/admin/settings"],
  ["🚀", "Launch Checklist", "/admin/launch"],
];
